### ISSUE TITLE
FYI: match_layers.py same size

### ISSUE THREAD

**Issue by jzju** [luigisaetta/whisper-app#1]
Saw that you got it working and it helped fix my failed attempt. Just want to say that there are stuff with the same size incase someday the model saves the weights in a different order.

'decoder.blocks.0.attn.value.weight': ('decoder.layers.0.self_attn.v_proj.weight', torch.Size([512, 512])),
'decoder.blocks.0.cross_attn.key.weight': ('decoder.layers.0.encoder_attn.k_proj.weight', torch.Size([512, 512])),
https://github.com/ggerganov/whisper.cpp/issues/157#issuecomment-1325654139

**Comment by luigisaetta** [comment]
HI @jzju actually to match the layers the code not only check the shape but also that the two layers have exactly the same parameters ( if torch.all(torch.eq(state_d_huggingface[j], state_d_standard[k])).item()). So, from the initial idea, it doesn't rely only on size. In any case, since I want to be sure that in the future I don't get mistakes, I have added more sanity checks:
* the two key must come both from encoder or decode
* the two key msut refer to the same layer number

**Comment by luigisaetta** [comment]
I think I can close this one. Thanks for the suggestions.

**Comment by luigisaetta** [comment]
Closed for now.
